### ISSUE TITLE
Documentation for traveling salesman (https://rl4co.readthedocs.io/en/latest/_collections/tutorials/2-creating-new-env-model.html)

### ISSUE THREAD

**Issue by paapu88** [ai4co/rl4co#103]
Dear Developers,
I'm confused by the first tutorial I came across in this repo:
https://rl4co.readthedocs.io/en/latest/_collections/tutorials/2-creating-new-env-model.html

It is said that it is a traveling salesman problem, but to me it looks like the 'cities' in the plot are moving between iterations.
If it some more generalised traveling salesman, what is optimised in the problem? 
Could you clarify this in the documentation?

Terveisin, Markus

**Comment by fedebotu** [comment]
Hi @paapu88 , this version of the TSP that we create from scratch in the notebook is the usual one, i.e. static version.

There are 3 plots in total. The first one contains one image only and actually is just for testing, the last 2 (with 3 images each) show initial solution guess by the untrained model and the trained version. You may check it out by comparing side by side (first untrained image to first trained, and so on):

| Initial solution     (untrained)                     | Solution after 3 training epochs                            |
| ----------------------------------- | ----------------------------------- |
| ![cat](https://rl4co.readthedocs.io/en/latest/_images/_collections_tutorials_2-creating-new-env-model_38_1.png) | ![dog](https://rl4co.readthedocs.io/en/latest/_images/_collections_tutorials_2-creating-new-env-model_42_1.png) |


| Initial solution     (untrained)                     | Solution after 3 training epochs                            |
| ----------------------------------- | ----------------------------------- |
| ![cat](https://rl4co.readthedocs.io/en/latest/_images/_collections_tutorials_2-creating-new-env-model_38_2.png) | ![dog](https://rl4co.readthedocs.io/en/latest/_images/_collections_tutorials_2-creating-new-env-model_42_2.png) |


| Initial solution     (untrained)                     | Solution after 3 training epochs                            |
| ----------------------------------- | ----------------------------------- |
| ![cat](https://rl4co.readthedocs.io/en/latest/_images/_collections_tutorials_2-creating-new-env-model_38_3.png) | ![dog](https://rl4co.readthedocs.io/en/latest/_images/_collections_tutorials_2-creating-new-env-model_42_3.png) |

**Comment by paapu88** [comment]
Thanks, now I see, your mapping was too difficult for me.
So below there are 3 pairs between the upper and lower sets.

![mapping](https://github.com/ai4co/rl4co/assets/6195764/8a28f9f8-78e6-4306-92f8-c4cc5fece9c9)

**Comment by fedebotu** [comment]
You're right, it was a bit confusing in hindsight. Now it should be fixed i.e. [here](https://github.com/ai4co/rl4co/blob/main/notebooks/tutorials/2-creating-new-env-model.ipynb) - documentation will get built later. What do you think?

**Comment by paapu88** [comment]
sorry, I cant see the difference???

**Comment by paapu88** [comment]
yes, thanks!
