### ISSUE TITLE
[BUG]'key "demand" not found in TensorDict with keys [\'action_mask\', \'current_node\', \'done\', \'first_node\', \'i\', \'locs\', \'reward\', \'terminated\']'

### ISSUE THREAD

**Issue by 1hhix** [ai4co/rl4co#104]
I encountered an issue in the file "rl4co-main\notebooks\tutorials\4-search-methods.ipynb," and it displayed "no demand."
```
env = TSPEnv(num_loc=50)
td = env.reset(batch_size=3).to(device)
out = policy(td, return_actions=True)
```
![image](https://github.com/ai4co/rl4co/assets/88278707/099d6beb-4183-41cd-8eb4-3165120afa08)

**Comment by 1hhix** [comment]
Yeah, I have already fixed the bugs. Thank you sincerely for your exceptional work. &nbsp;🎉🎉🎉


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ai4co/rl4co"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月6日(星期三) 下午5:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ai4co/rl4co] [BUG]'key "demand" not found in TensorDict with keys [\'action_mask\', \'current_node\', \'done\', \'first_node\', \'i\', \'locs\', \'reward\', \'terminated\']' (Issue #104)





 
Hi @1hhix, sorry we are a bit late in answering.
 Have you figured out the bug?
 In that case, we checked and it was probably because the EAS model was trained on SDVRP (from here), but not on TSP, thus raising the "demand not found" error

**Comment by fedebotu** [comment]
Glad to hear that :) Don't hesitate to contact us if you find any issue~
