### ISSUE TITLE
[Please add the am-critic, POMO, and POMO models under the op question to the experiment/archive/ folder]

### ISSUE THREAD

**Issue by lihaoya5** [ai4co/rl4co#136]
## Motivation

I'm more interested in the OP problem, I saw that your paper about the OP problem is solved with multiple models such as AM, but there is only the AM model implementation under the experiment/archive folder, I have just run it again, and the effect is very good. Can you upload the other model methods in the paper？
![image](https://github.com/ai4co/rl4co/assets/147461554/93d51413-08c5-4a09-9b49-54d31950b4de)

**Comment by fedebotu** [comment]
Problem solved, please follow the new instructions [here](https://github.com/ai4co/rl4co/tree/main/configs/experiment#readme)! 👍
