### ISSUE TITLE
Add flexible shop scheduling environment

### ISSUE THREAD

**Issue by lshengjian** [ai4co/rl4co#168]
Add flexible shop scheduling environment.

**Comment by lshengjian** [comment]
FJSP
> Hi @lshengjian! Do you mean the _flexible flow-shop scheduling problem_ (FFSP) or the _flexible job-shop scheduling problem_ (FJSP)?
> 
> If it's the former, we have supported it:
> 
> https://github.com/ai4co/rl4co/blob/97e90b999e0defb698d56bfd54a0ba207b1a3455/rl4co/envs/scheduling/ffsp.py#L19-L21
> 
> 
> If it's the FJSP, we don't have it in the current version. If you want, you could have a look at this [tutorial](https://github.com/ai4co/rl4co/blob/main/examples/3-creating-new-env-model.ipynb) to try to implement it.
> Feel free to inform us if you have further questions!



> Add flexible shop scheduling environment.

**Comment by fedebotu** [comment]
I think @LTluttmann should have an implementation that is almost working, right?

**Comment by lshengjian** [comment]
https://github.com/google/or-tools/blob/stable/examples/python/flexible_job_shop_sat.py

**Comment by LTluttmann** [comment]
> I think @LTluttmann should have an implementation that is almost working, right?

exactly, FJSP will be added to RL4CO soon :)
