### ISSUE TITLE
[Can you provide the environment for python=3.9.18？]

### ISSUE THREAD

**Issue by lihaoya5** [ai4co/rl4co#178]
## Motivation
When I was researching the torchquantum framework, I found that it is based on python 3.7 ~ pthon 3.9, but I only have a working environment version of python 3.11 for rl4co that you provided earlier. I want to solve the CO problem with the quantum transformer module under the torchquantum framework.

## Solution
If you have a previous version of Python 3.9 that can run RL4CO, could you please provide us with python=? RL4CO=? pyTorch=? What is the version number of Torch Geometric=?? Thank you.

**Comment by fedebotu** [comment]
Hi there! We should be pretty flexible, so you may try installing RL4CO inside your python environment and should work out of the box without restrictions on specific versions

**Comment by lihaoya5** [comment]
Okay, I'll try it, thanks

**Comment by fedebotu** [comment]
Closing now as it should be resolved. Feel free to re-open or file a new issue if something is still not working!
