### ISSUE TITLE
[BUG] Find a mistake in docs

### ISSUE THREAD

**Issue by Rubbin1926** [ai4co/rl4co#198]
In the "NEW ENVIRONMENT: CREATING AND MODELING" - "Imports" chapter:
[https://rl4co.readthedocs.io/en/latest/_collections/3-creating-new-env-model.html](https://rl4co.readthedocs.io/en/latest/_collections/3-creating-new-env-model.html)

```python
from rl4co.envs.common import RL4COEnvBase, Generator, get_sampler
```

But _RL4COEnvBase_ is actually in rl4co.envs.common.base
_Generator, get_sampler_ are in rl4co.envs.common.utils

So maybe the correct one is:

```python
from rl4co.envs.common.base import RL4COEnvBase
from rl4co.envs.common.utils import Generator, get_sampler
```

**Comment by ngastzepeda** [comment]
You will notice that in rl4co.envs.common there is a file called `__init__.py`. The files you mention are imported here, which allows us to directly do `from rl4co.envs.common import RL4COEnvBase, Generator, get_sampler`.
