### ISSUE TITLE
Error while trying to train multiple models for TSP of size 20 and 50. 

### ISSUE THREAD

**Issue by ujjwaldasari10** [ai4co/rl4co#205]
## Describe the bug

I used the quickstart example to train TSP of size 20 in a conda environment on a gpu connected via SSH in VS code Jupyter notebook. But when I am trying to train a new TSP model of size 50 in the same  folder from scratch and trying to load the render the dataset , I am still getting dataset of size 20 instead of 50. The model trains fine but even the below lines seem to only generate Dataset of size 20 instead of 50:

env = TSPEnv( num_loc = 50)
new_dataset = env.dataset(10000)
dataloader = model._dataloader(new_dataset, batch_size=100)
print(new_dataset[0]["locs"].shape)

Output:
Unused keyword arguments: num_loc. Please check the documentation for the correct keyword arguments
torch.Size([20, 2])

I tried running a new jupyter notebook of size 50 in a new folder but the problem still persists. Can you please helop me identify the issue?

**Comment by fedebotu** [comment]
The reason is that we changed the API: now we have a separate `Generator` class that handles the data generation. So you may call it like this:
```python
env = TSPEnv(generator_params={'num_loc': 50})
```
(example [here](https://rl4.co/examples/1-quickstart/#imports:~:text=env%20%3D%20TSPEnv(generator_params%3D%7B%27num_loc%27%3A%2050%7D)))

**Comment by cbhua** [comment]
Yes. You could set the trining with multi GPUs by editing the parameter `trainer.devices`. 

For example, if you want to try the example experiment in the README (AM on TSP) with multiple GPUs, you can launch the training with 

```bash
python run.py +trainer.devices="[0, 1]"
```

This training will use `coda:0` and `coda:1`. And you can set it to more devices if you want. 

Here are some useful materials you may want to refer to:

1. [RL4CO trainer tutorial](https://rl4.co/examples/2-full-training/#logging:~:text=The%20RL4CO%20trainer%20is%20a%20wrapper%20around%20PyTorch%20Lightning%27s%20Trainer%20class%20which%20adds%20some%20functionality%20and%20more%20efficient%20defaults).
2. [Hydra config tutorial](https://rl4.co/examples/advanced/1-hydra-config/).

**Comment by ujjwaldasari10** [comment]
Do you guys plan on including MCTS in the list of decoding strategies in the near future?

**Comment by fedebotu** [comment]
@ujjwaldasari10 We are not planning to in the near future since MCTS has not been applied much in the NCO literature, such as routing and scheduling. I remember some work that did, but other methods outperformed it without MCTS.

I think that is an interesting direction, and we gladly accept contributions! If you are interested, I invite you to give it a shot :)
What kind of problem would you like to use it for?

**Comment by fedebotu** [comment]
Note: closing issue now, @ujjwaldasari10 about MCTS, if you are interested feel free to open a new discussion [here](https://github.com/ai4co/rl4co/discussions) or contact us on Slack :rocket:
