### ISSUE TITLE
Can't train with the quickstart notebook

### ISSUE THREAD

**Issue by Farouc** [ai4co/rl4co#208]
I have tried to run the quickstart notebook in colab and i couldn't train the model.

The error is the following:
![bug](https://github.com/user-attachments/assets/815593ee-f6b3-489a-b787-b4ef06b2e464)

**Comment by fedebotu** [comment]
Hi @Farouc!

This could be due to the updated version of Tensordict. Could you try installing `rl4co` from source?

```python
!pip install -U git+https://github.com/ai4co/rl4co.git
```

The reason is that Tensordict was recently updated. We will push the major release to PyPI in the next couple of days!

**Comment by fedebotu** [comment]
@Farouc the new version is out! Now you should be able to run the original notebook without the above installation from source :)

**Comment by Farouc** [comment]
Thank you for your response !!
