### ISSUE TITLE
[Feature Request]Epoch 0/99 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/2500 0:00:00 • -:--:-- 0.00it/s v_num: o801 val/reward: -17.800  

### ISSUE THREAD

**Issue by Ynantao** [ai4co/rl4co#213]
## Motivation

Please outline the motivation for the proposal.
Is your feature request related to a problem? e.g., "I'm always frustrated when [...]".
If this is related to another issue, please link here too.

## Checklist

- [ ] I have checked that there is no similar issue in the repo (**required**)

**Comment by fedebotu** [comment]
Hi, I think this may have been accidentally submitted / not formatted yet?

**Comment by Ynantao** [comment]
Sorry, I didn't see any response for a while and thought it was stuck. It turns out my training is just too slow.
