### ISSUE TITLE
Is it possible to generate and load trainning data to the model at every epoch?

### ISSUE THREAD

**Issue by ujjwaldasari10** [ai4co/rl4co#216]
Its not a bug exactly, more like a doubt.
Is it possible to generate and pass training data to the model at every epoch? Increasing the training data_size using the Attention Model class(given below) is causing Out of memory issues for me:  
model = AttentionModel(env,baseline="rollout", train_data_size=1000_000,val_data_size=10_000,optimizer_kwargs={"lr": 1e-4},).
Thanks in advance.

**Comment by fedebotu** [comment]
Hi @ujjwaldasari10!
Yes, this can be achieved in several ways. For example, by using the `RL4COLitModule` `on_train_epoch_end` callback, we generate a dataset for each epoch to train on [here](https://github.com/ai4co/rl4co/blob/b516158a238537b03534ee1453f325fa140e47ec/rl4co/models/rl/common/base.py#L281).


Note that the `train_data_size` (i.e., number of instances per epoch) can be adjusted. Keeping the total number of samples the same, you can do, say 10,000 instances/epoch for 1000 epochs or 100,000 for 100 epochs and if the dataset cannot fit into memory
