### ISSUE TITLE
About TSP data format

### ISSUE THREAD

**Issue by cclvr2** [ai4co/rl4co#233]
Thank you very much for developing this library. 

My question is: if a TSP problem is defined not by 2D coordinates but by the distances between points,  can the existing dataset API be used? Is there a way to handle this scenario?

Looking forward to your replay.

**Comment by fedebotu** [comment]
Hi! Yes, but you need to change the model structure to handle edges. For example, [MatNet](https://rl4.co/docs/content/api/zoo/constructive_ar/?h=matnet#models.zoo.matnet.policy.MatNetPolicy) can deal with edge features. The [ATSP](https://rl4.co/docs/content/api/envs/routing/?h=atsp#envs.routing.atsp.env.ATSPEnv) environment also handles them

**Comment by cclvr2** [comment]
> Hi! Yes, but you need to change the model structure to handle edges. For example, [MatNet](https://rl4.co/docs/content/api/zoo/constructive_ar/?h=matnet#models.zoo.matnet.policy.MatNetPolicy) can deal with edge features. For the environment, you may use the [ATSP](https://rl4.co/docs/content/api/envs/routing/?h=atsp#envs.routing.atsp.env.ATSPEnv) environment to handle them

Thanks a lot for your quick replay, I' try it.
